{{- if ((.Values.podDisruptionBudget).enabled) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "sentinel.fullname" . }}
  labels:
    {{- include "sentinel.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "sentinel.selectorLabels" . | nindent 6 }}
{{- end }}
